FactoryBot.define do
  factory :user do
    full_name { "Fulana da Silva" }
    document { "11122233344" }
    address { "Rua Da Minha Casa, 100" }
    birthday { "1990-01-01" }
    gender { "F" }
    password { "12345678" }
    token { "mYauTOGeneRaTeDDuMMyToKen" }
  end
end
