require 'rails_helper'

RSpec.describe AccountLimitUpdateService do
  subject do
    described_class.new(update_limit_params)
  end

  let(:update_limit_params) do
    {
      token: 'mYauTOGeneRaTeDDuMMyToKen',
      amount: 2500.0
    }
  end

  let(:user) { create(:user) }
  let(:account) { create(:account) }

  describe '#update' do
    context 'quando passou 10 minutos ou mais desde a última atualização' do
      before do
        past_time = Time.zone.now - 600
        account.update(last_limit_update: past_time)
      end

      context 'quando o valor em conta é menor ou igual ao limite escolhido' do
        it 'altera valor do limite' do
          subject.update

          expect(account.reload.limit).to eq(2500.0)
        end

        it 'altera última data de atualização' do
          expect { subject.update }.to change { account.reload.last_limit_update }
        end
      end

      context 'quando o valor em conta é maior que o limite escolhido' do
        before do
          account.update(balance: 2700.0)
        end

        it 'não altera valor do limite' do
          expect { subject.update }.not_to change { account.reload.limit }
        end
      end
    end

    context 'quando passou menos de 10 minutos desde a última atualização' do
      before do
        past_time = Time.zone.now - 500
        account.update(last_limit_update: past_time)
      end

      it 'não altera valor do limite' do
        expect { subject.update }.not_to change { account.reload.limit }
      end
    end
  end

  describe '.update' do
    it 'inicia o serviço, executa e retorna o resultado de #update' do
      service = instance_double('AccountLimitUpdateService')
      account = instance_double('Account')

      expect(described_class).to receive(:new).with(update_limit_params).once.and_return(service)
      expect(service).to receive(:update).and_return(account)

      expect(described_class.update(update_limit_params)).to eq(account)
    end
  end
end
